Repository Co-Laon/claon-server, pull requests merged in 2022-09, with the labels that each got.

#228 refac: refactor add crayon url for center
  src/main/java/coLaon/ClaonBack/center/dto/HoldInfoResponseDto.java
Labels: refactor

#229 refac: add body information column of user table
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/IndividualUserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserModifyRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/domain/UserTest.java
  src/test/java/coLaon/ClaonBack/repository/BlockUserRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/CenterBookmarkRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/LaonRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/NoticeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/ReviewRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/UserRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/NoticeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#232 refac: remove find user in each api
  src/main/java/coLaon/ClaonBack/center/service/CenterBookmarkService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/common/utils/JwtUtil.java
  src/main/java/coLaon/ClaonBack/config/JwtAuthFilter.java
  src/main/java/coLaon/ClaonBack/config/JwtAuthenticationEntryPoint.java
  src/main/java/coLaon/ClaonBack/config/UserAccount.java
  src/main/java/coLaon/ClaonBack/notice/service/NoticeService.java
  src/main/java/coLaon/ClaonBack/notice/web/NoticeController.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/post/web/WriterController.java
  src/main/java/coLaon/ClaonBack/user/domain/Laon.java
  src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/main/java/coLaon/ClaonBack/user/web/LaonController.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/repository/LaonRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/NoticeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#238 Ci test
  .github/workflows/ci.yml
Labels: chore, refactor

#235 refactor: remove useless nickname check
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java
Labels: refactor

#230 feat: add to delete user
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReport.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/domain/PostComment.java
  src/main/java/coLaon/ClaonBack/post/domain/PostLike.java
  src/main/java/coLaon/ClaonBack/post/domain/PostReport.java
  src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java
  src/main/java/coLaon/ClaonBack/user/domain/Laon.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: enhancement, refactor

#243 feat: find home posts
  build.gradle
  src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/HomeController.java
  src/main/java/coLaon/ClaonBack/version/repository/AppVersionRepository.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: enhancement

#247 refac: seperate sector info with table
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java
  src/main/java/coLaon/ClaonBack/center/domain/converter/SectorInfoListConverter.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterBookmarkResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/SectorInfoDto.java
  src/main/java/coLaon/ClaonBack/center/dto/SectorInfoRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/SectorInfoResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/SectorInfoRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/test/java/coLaon/ClaonBack/repository/CenterBookmarkRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/HoldInfoRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/ReviewRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#242 feat: apply on delete
  src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReport.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java
  src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java
  src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/domain/PostComment.java
  src/main/java/coLaon/ClaonBack/post/domain/PostLike.java
  src/main/java/coLaon/ClaonBack/post/domain/PostReport.java
  src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java
  src/main/java/coLaon/ClaonBack/user/domain/Laon.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
Labels: enhancement

#248 fix: fix bean create exception in jwt authentication filter
  src/main/java/coLaon/ClaonBack/config/JwtAuthenticationEntryPoint.java
  src/main/java/coLaon/ClaonBack/config/JwtAuthenticationFilter.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
Labels: fix

#249 fix: change column name in sector info table about postgresql issue
  src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java
Labels: fix

#250 fix: fix bug null point exception in sector info response dto
  src/main/java/coLaon/ClaonBack/center/dto/SectorInfoResponseDto.java
Labels: fix

#244 feat: implement search user and center by name
  src/main/java/coLaon/ClaonBack/center/domain/enums/CenterSearchOption.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterNameResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterSearchResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepositorySupport.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/user/dto/UserPreviewResponseDto.java
  src/main/java/coLaon/ClaonBack/user/repository/UserRepositorySupport.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/UserRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: enhancement

#252 refac: except block relation when read laon list
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepositorySupport.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/test/java/coLaon/ClaonBack/repository/LaonRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
Labels: refactor

#251 feat: implement search center for new setting
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepositorySupport.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
Labels: enhancement

#253 refac: modify cors configuration for cookie
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
Labels: refactor

#256 refac: change token location cookie to header
  src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java
  src/main/java/coLaon/ClaonBack/common/utils/HeaderUtil.java
  src/main/java/coLaon/ClaonBack/config/JwtAuthenticationFilter.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
Labels: refactor
