Repository Co-Laon/claon-server, pull requests merged in 2022-06, with the labels that each got.

#26 feat: configure Swagger3
  build.gradle
  src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
Labels: enhancement

#27 Feature/exception
  src/main/java/coLaon/ClaonBack/exception/BadRequestException.java
  src/main/java/coLaon/ClaonBack/exception/BaseRuntimeException.java
  src/main/java/coLaon/ClaonBack/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/exception/UnauthorizedException.java
Labels: enhancement

#29 feat: implement validation model (#17)
  src/main/java/coLaon/ClaonBack/application/validator/IdEqualValidator.java
  src/main/java/coLaon/ClaonBack/application/validator/IsDeletedValidator.java
  src/main/java/coLaon/ClaonBack/application/validator/Validator.java
Labels: enhancement

#30 feat: sign up for user
  build.gradle
  src/main/java/coLaon/ClaonBack/common/domain/BaseEntity.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/Address.java
  src/main/java/coLaon/ClaonBack/common/exception/BadRequestException.java
  src/main/java/coLaon/ClaonBack/common/exception/BaseRuntimeException.java
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/common/exception/UnauthorizedException.java
  src/main/java/coLaon/ClaonBack/common/validator/IdEqualValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/IsDeletedValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/PasswordFormatValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/Validator.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/main/resources/application-local.yml
  src/test/java/coLaon/ClaonBack/ClRaonBackApplicationTests.java
Labels: enhancement

#32 refac: refactor code for sign up
  src/main/java/coLaon/ClaonBack/common/domain/enums/Address.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/BasicLocalArea.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/MetropolitanArea.java
  src/main/java/coLaon/ClaonBack/common/validator/IdEqualValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/IsDeletedValidator.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
Labels: refactor

#36 docs: fix organization name in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#37 feat: implement duplicated check for email and nickname
  src/main/java/coLaon/ClaonBack/user/dto/DuplicatedCheckResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
Labels: enhancement

#35 feat: implement test code template with sign up test code
  build.gradle
  src/main/java/coLaon/ClaonBack/ClaonBackApplication.java
  src/main/java/coLaon/ClaonBack/common/domain/BaseEntity.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/AuthServiceTest.java
Labels: enhancement

#52 feat: Add laon and like and comment entity
  src/main/java/coLaon/ClaonBack/laon/Service/LaonService.java
  src/main/java/coLaon/ClaonBack/laon/domain/Laon.java
  src/main/java/coLaon/ClaonBack/laon/domain/LaonComment.java
  src/main/java/coLaon/ClaonBack/laon/domain/LaonLike.java
  src/main/java/coLaon/ClaonBack/laon/repository/LaonCommentRepository.java
  src/main/java/coLaon/ClaonBack/laon/repository/LaonLikeRepository.java
  src/main/java/coLaon/ClaonBack/laon/repository/LaonRepository.java
  src/main/java/coLaon/ClaonBack/laon/web/LaonController.java
  src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java
Labels: enhancement

#34 feat: email sending service (#14)
  .gitignore
  build.gradle
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/common/exception/InternalServerErrorException.java
  src/main/java/coLaon/ClaonBack/common/exception/UnavailableMailServerException.java
  src/main/java/coLaon/ClaonBack/common/infrastructure/EmailSender.java
  src/main/java/coLaon/ClaonBack/config/EmailSenderConfig.java
  src/main/resources/application-local.yml
Labels: enhancement

#55 feat: relative time string converter (#47)
  src/main/java/coLaon/ClaonBack/common/infrastructure/RelativeTimeString.java
Labels: enhancement

#54 feat: create like
  src/main/java/coLaon/ClaonBack/common/domain/BaseEntity.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/BasicLocalArea.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/MetropolitanArea.java
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/laon/Service/LaonService.java
  src/main/java/coLaon/ClaonBack/laon/domain/Laon.java
  src/main/java/coLaon/ClaonBack/laon/domain/LaonComment.java
  src/main/java/coLaon/ClaonBack/laon/domain/LaonLike.java
  src/main/java/coLaon/ClaonBack/laon/dto/LikeRequestDto.java
  src/main/java/coLaon/ClaonBack/laon/dto/LikeResponseDto.java
  src/main/java/coLaon/ClaonBack/laon/web/LaonController.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/test/java/coLaon/ClaonBack/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/LaonServiceTest.java
Labels: enhancement

#58 feat: Implement create comment
  src/main/java/coLaon/ClaonBack/laon/Service/LaonCommentService.java
  src/main/java/coLaon/ClaonBack/laon/domain/LaonComment.java
  src/main/java/coLaon/ClaonBack/laon/dto/CommentRequestDto.java
  src/main/java/coLaon/ClaonBack/laon/dto/CommentResponseDto.java
  src/main/java/coLaon/ClaonBack/laon/web/LaonController.java
  src/test/java/coLaon/ClaonBack/LaonCommentServiceTest.java
Labels: enhancement
