Repository Co-Laon/claon-server, pull requests merged in 2022-08, with the labels that each got.

#170 fix : modify to create multiple reviews for one center
  src/main/java/coLaon/ClaonBack/center/dto/ReviewCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/post/repository/ReviewRepository.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
Labels: fix

#155 feat: find center review
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java
  src/main/java/coLaon/ClaonBack/center/dto/ReviewFindResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/ReviewListFindResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/ReviewResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/ReviewUpdateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/post/repository/ReviewRepository.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
Labels: enhancement

#166 feat: implement bookmark center create and delete (#115)
  src/main/java/coLaon/ClaonBack/center/domain/BookmarkCenter.java
  src/main/java/coLaon/ClaonBack/center/dto/BookmarkCenterResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/BookmarkCenterRepository.java
  src/main/java/coLaon/ClaonBack/center/service/BookmarkCenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/test/java/coLaon/ClaonBack/service/BookmarkCenterServiceTest.java
Labels: enhancement

#171 refac: add climbing history size validator for create post
  src/main/java/coLaon/ClaonBack/common/validator/ClimbingHistorySize.java
  src/main/java/coLaon/ClaonBack/common/validator/ClimbingHistorySizeValidator.java
  src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
Labels: refactor

#173 feat: center find
  src/main/java/coLaon/ClaonBack/center/dto/CenterDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterSearchResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
Labels: enhancement

#176 refac: refactor for get other user information
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#184 refac: refactor for service package by domain
  src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterBookmarkResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterBookmarkRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterBookmarkService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#178 feat: implement user posts
  src/main/java/coLaon/ClaonBack/center/dto/HoldInfoResponseDto.java
  src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java
  src/main/java/coLaon/ClaonBack/common/exception/NotFoundException.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostThumbnailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java
  src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: enhancement

#182 fix: fix laon myself and block myself
  src/main/java/coLaon/ClaonBack/common/validator/NotIdEqualValidator.java
  src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java
  src/main/java/coLaon/ClaonBack/user/domain/Laon.java
  src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: fix

#179 feat: set multipart resolver configuration
  build.gradle
  src/main/java/coLaon/ClaonBack/config/MultipartResolverConfig.java
Labels: enhancement

#185 refac: refactor constructor of domain
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java
  src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterBookmarkResponseDto.java
  src/main/java/coLaon/ClaonBack/post/domain/ClimbingHistory.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/domain/PostComment.java
  src/main/java/coLaon/ClaonBack/post/domain/PostContents.java
  src/main/java/coLaon/ClaonBack/post/domain/PostLike.java
  src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#189 refac: add querydsl example for post and center review
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepository.java
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java
  src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
Labels: fix, refactor

#188 refac: refactor to appropriate exception according to the error situation
  src/main/java/coLaon/ClaonBack/center/service/CenterBookmarkService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: refactor

#187 feat: implement app version confirmation (#161)
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/version/domain/AppVersion.java
  src/main/java/coLaon/ClaonBack/version/dto/AppVersionFindResponseDto.java
  src/main/java/coLaon/ClaonBack/version/repository/AppVersionRepository.java
  src/main/java/coLaon/ClaonBack/version/service/AppVersionService.java
  src/main/java/coLaon/ClaonBack/version/web/AppVersionController.java
  src/test/java/coLaon/ClaonBack/repository/AppVersionRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/AppVersionServiceTest.java
Labels: enhancement

#193 fix: fix bug in get user posts about my page
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/post/web/WriterController.java
  src/main/java/coLaon/ClaonBack/version/domain/AppStore.java
  src/main/java/coLaon/ClaonBack/version/service/AppVersionService.java
  src/main/java/coLaon/ClaonBack/version/web/AppVersionController.java
  src/test/java/coLaon/ClaonBack/service/AppVersionServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: fix

#201 fix: fix bug of querydsl subquery
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java
Labels: fix

#199 feat: implement center list api
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterListOption.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterPreviewResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
Labels: enhancement

#209 refac: refactor charge list of center
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/Charge.java
  src/main/java/coLaon/ClaonBack/center/domain/ChargeElement.java
  src/main/java/coLaon/ClaonBack/center/domain/converter/ChargeListConverter.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterBookmarkResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/ChargeDto.java
  src/main/java/coLaon/ClaonBack/center/dto/ChargeElementDto.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostContentsRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#196 refac: refactor find all like by post without block user
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java
  src/test/java/coLaon/ClaonBack/config/QueryDslTestConfig.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
Labels: refactor

#198 refac: refactor find all comment without block user
  src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java
  src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
Labels: refactor

#206 refac: refactor s3 image upload method for resizing image
  build.gradle
  src/main/java/coLaon/ClaonBack/common/utils/ImageUtil.java
  src/main/java/coLaon/ClaonBack/common/utils/S3Util.java
  src/main/java/coLaon/ClaonBack/common/validator/IsImageValidator.java
Labels: refactor

#207 feat: find posts by center with hold info
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java
  src/main/java/coLaon/ClaonBack/common/validator/IsHoldValidator.java
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: enhancement

#214 refac: refactor center create request dto for null
  src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
Labels: refactor

#217 feat: implement create center report
  src/main/java/coLaon/ClaonBack/center/domain/CenterReport.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReportType.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterReportCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterReportResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterReportRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
Labels: enhancement

#215 feat: implement notice
  src/main/java/coLaon/ClaonBack/notice/domain/Notice.java
  src/main/java/coLaon/ClaonBack/notice/dto/NoticeCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/notice/dto/NoticeResponseDto.java
  src/main/java/coLaon/ClaonBack/notice/repository/NoticeRepository.java
  src/main/java/coLaon/ClaonBack/notice/service/NoticeService.java
  src/main/java/coLaon/ClaonBack/notice/web/NoticeController.java
  src/test/java/coLaon/ClaonBack/repository/NoticeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/NoticeServiceTest.java
Labels: enhancement

#216 feat: create post report
  src/main/java/coLaon/ClaonBack/post/domain/PostReport.java
  src/main/java/coLaon/ClaonBack/post/domain/enums/ReportType.java
  src/main/java/coLaon/ClaonBack/post/dto/ReportRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/ReportResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostReportRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: enhancement

#218 fix: fix concurrency bug about rank of center
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterPreviewResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/ReviewListFindResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepositorySupport.java
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepository.java
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java
  src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/test/java/coLaon/ClaonBack/repository/CenterRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/ReviewRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
Labels: fix, refactor

#219 refac: refactor post contents and entity column constraint
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java
  src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java
  src/main/java/coLaon/ClaonBack/post/domain/ClimbingHistory.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/domain/PostContents.java
  src/main/java/coLaon/ClaonBack/post/domain/converter/PostContentsConverter.java
  src/main/java/coLaon/ClaonBack/post/dto/PostContentsDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostContentsRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostContentsRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#220 refac: add string to enum converter
  src/main/java/coLaon/ClaonBack/center/domain/CenterReportType.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterReportCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterSearchOption.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/converter/CenterReportTypeConverter.java
  src/main/java/coLaon/ClaonBack/center/web/converter/CenterSearchOptionConverter.java
  src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/MetropolitanArea.java
  src/main/java/coLaon/ClaonBack/config/WebConfig.java
  src/main/java/coLaon/ClaonBack/notice/domain/Notice.java
  src/main/java/coLaon/ClaonBack/notice/dto/NoticeCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/notice/dto/NoticeResponseDto.java
  src/main/java/coLaon/ClaonBack/notice/repository/NoticeRepository.java
  src/main/java/coLaon/ClaonBack/notice/service/NoticeService.java
  src/main/java/coLaon/ClaonBack/notice/web/NoticeController.java
  src/main/java/coLaon/ClaonBack/post/domain/PostReport.java
  src/main/java/coLaon/ClaonBack/post/domain/enums/PostReportType.java
  src/main/java/coLaon/ClaonBack/post/domain/enums/ReportType.java
  src/main/java/coLaon/ClaonBack/post/dto/PostReportRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostReportResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/ReportRequestDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/post/web/converter/PostReportTypeConverter.java
  src/main/java/coLaon/ClaonBack/user/domain/OAuth2Provider.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserModifyRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/main/java/coLaon/ClaonBack/user/web/converter/MetropolitanAreaConverter.java
  src/main/java/coLaon/ClaonBack/user/web/converter/OAuth2ProviderConverter.java
  src/main/java/coLaon/ClaonBack/version/domain/AppStore.java
  src/main/java/coLaon/ClaonBack/version/service/AppVersionService.java
  src/main/java/coLaon/ClaonBack/version/web/AppVersionController.java
  src/main/java/coLaon/ClaonBack/version/web/converter/AppStoreConverter.java
  src/test/java/coLaon/ClaonBack/repository/NoticeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/AppVersionServiceTest.java
  src/test/java/coLaon/ClaonBack/service/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/NoticeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#221 fix: fix bug about charge list
  src/main/java/coLaon/ClaonBack/center/domain/converter/ChargeListConverter.java
Labels: fix

#222 fix: fix bug about charge list
  src/main/java/coLaon/ClaonBack/center/domain/converter/ChargeListConverter.java
Labels: fix

#224 fix: fix bug of enum in request body
  src/main/java/coLaon/ClaonBack/center/domain/CenterReportType.java
  src/main/java/coLaon/ClaonBack/center/web/converter/CenterReportTypeConverter.java
  src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/MetropolitanArea.java
  src/main/java/coLaon/ClaonBack/config/WebConfig.java
  src/main/java/coLaon/ClaonBack/post/domain/enums/PostReportType.java
  src/main/java/coLaon/ClaonBack/post/web/converter/PostReportTypeConverter.java
  src/main/java/coLaon/ClaonBack/user/web/converter/MetropolitanAreaConverter.java
Labels: fix
