Repository Co-Laon/claon-server, pull requests merged in 2022-10, with the labels that each got.

#258 feat: add exposed header for reponse header
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
Labels: refactor

#260 fix: change request parameter to request part for image upload
  src/main/java/coLaon/ClaonBack/storage/web/StorageController.java
Labels: fix

#263 refac: modify individual page and mypage
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/post/dto/CenterClimbingHistoryResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostThumbnailResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/CenterPreviewResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/IndividualUserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#266 refac: remove writer controller
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java
  src/main/java/coLaon/ClaonBack/post/web/WriterController.java
  src/main/java/coLaon/ClaonBack/user/dto/PostThumbnailResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/PostPort.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#270 refac: refactor read service about center posts for package dependency
  src/main/java/coLaon/ClaonBack/center/dto/PostThumbnailResponseDto.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/service/PostPort.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/post/dto/PostThumbnailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/service/PostToCenterAdapter.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/dto/PostThumbnailResponseDto.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: refactor

#268 refac: remove cyclic dependency between user and post module
  src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java
  src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java
  src/main/java/coLaon/ClaonBack/user/dto/CenterClimbingHistoryResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/ClimbingHistoryResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/HoldInfoResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/IndividualUserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/PostThumbnailResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/PostPort.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#271 refac: refactor endpoint in users
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java
  src/main/java/coLaon/ClaonBack/post/web/HomeController.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/dto/PostDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/service/PostPort.java
  src/main/java/coLaon/ClaonBack/user/web/LaonController.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/repository/UserRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: refactor

#275 refac: remove storage directory
  src/main/java/coLaon/ClaonBack/common/utils/S3Util.java
  src/main/java/coLaon/ClaonBack/storage/domain/enums/ImagePurpose.java
  src/main/java/coLaon/ClaonBack/storage/service/StorageService.java
  src/main/java/coLaon/ClaonBack/storage/web/StorageController.java
  src/main/java/coLaon/ClaonBack/user/infra/ProfileImageUploader.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
Labels: refactor

#284 fix: change jwt filter genericfileterbean to onceperrequestfilter
  src/main/java/coLaon/ClaonBack/config/JwtAuthenticationFilter.java
Labels: fix

#285 feat: add apache config for https
  src/main/resources/application-prod.yml
Labels: enhancement

#286 fix: fix authenticationprincipal not visible in swagger
  src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
Labels: fix

#288 fix: modify to include headers in swagger
  src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
Labels: fix

#289 fix: change arm reach and height to be null-safe
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserModifyRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
Labels: fix

#291 refac: query optimization for find block users
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepositorySupport.java
  src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java
  src/main/java/coLaon/ClaonBack/user/dto/BlockUserFindResponseDto.java
  src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java
  src/main/java/coLaon/ClaonBack/user/service/BlockUserService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/repository/BlockUserRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
Labels: refactor
