Repository Co-Laon/claon-server, pull requests merged in 2022-11, with the labels that each got.

#293 refac: change pageable to custom class for swagger
  src/main/java/coLaon/ClaonBack/common/domain/SwaggerPageable.java
  src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
Labels: refactor

#280 feat: implement delete for profile image (#259)
  src/main/java/coLaon/ClaonBack/common/utils/S3Util.java
  src/main/java/coLaon/ClaonBack/user/infra/ProfileImageManager.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
Labels: enhancement

#294 refac: refactor page number of pagination
  src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java
Labels: refactor

#295 fix: fix bug about all controller
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/notice/web/NoticeController.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/dto/SignInRequestDto.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/main/java/coLaon/ClaonBack/user/web/LaonController.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
Labels: fix

#296 refac: add isLike to dto about post detail
  src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java
  src/main/java/coLaon/ClaonBack/user/dto/UserPostDetailResponseDto.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
Labels: refactor

#298 feat: return token for test
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/user/dto/TestSignInRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
Labels: enhancement

#300 fix: fix bug about jackson and lombok
  src/main/java/coLaon/ClaonBack/user/dto/TestSignInRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
Labels: fix

#306 feat: add cd in github actions
  .github/workflows/cd.yml
Labels: enhancement

#301 feat: implement delete s3 image for post contents using image path
  src/main/java/coLaon/ClaonBack/common/utils/S3Util.java
  src/main/java/coLaon/ClaonBack/common/validator/IsExistUrlValidator.java
  src/main/java/coLaon/ClaonBack/post/dto/PostContentsUrlDto.java
  src/main/java/coLaon/ClaonBack/post/infra/PostContentsImageManager.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/infra/ProfileImageManager.java
Labels: enhancement

#310 fix: fix bug about order of post climbing histories
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java
  src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#312 refac: fix naming collapse CenterPreviewResponseDto
  src/main/java/coLaon/ClaonBack/post/service/PostToUserAdapter.java
  src/main/java/coLaon/ClaonBack/user/dto/CenterClimbingHistoryResponseDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserCenterPreviewResponseDto.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#307 refac: wrap review dto to divide reviews by writer (#290)
  src/main/java/coLaon/ClaonBack/center/dto/ReviewBundleFindResponseDto.java
  src/main/java/coLaon/ClaonBack/center/repository/ReviewRepositorySupport.java
  src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/test/java/coLaon/ClaonBack/repository/ReviewRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
Labels: refactor

#304 refac: refactor error message
  src/main/java/coLaon/ClaonBack/center/domain/enums/CenterReportType.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterReportCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/ReviewCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/repository/HoldInfoRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterBookmarkService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterReviewService.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/common/utils/S3Util.java
  src/main/java/coLaon/ClaonBack/common/validator/IsHoldValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/IsImageValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/IsPrivateValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/NotIdEqualValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/UserNickname.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/notice/dto/NoticeCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/domain/enums/PostReportType.java
  src/main/java/coLaon/ClaonBack/post/dto/ClimbingHistoryRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/CommentCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostContentsDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostReportRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostUpdateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/TestSignInRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/main/java/coLaon/ClaonBack/version/service/AppVersionService.java
  src/test/java/coLaon/ClaonBack/repository/HoldInfoRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/BlockUserServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterBookmarkServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterReviewServiceTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#308 refac: validate laon user is blocked to create laon
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
Labels: refactor

#313 refac: refactor response dto of retrieve me api
  src/main/java/coLaon/ClaonBack/user/dto/UserDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#297 refac: query optimization for N+1 issue
  src/main/java/coLaon/ClaonBack/center/domain/CenterBookmark.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterReview.java
  src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/domain/PostComment.java
  src/main/java/coLaon/ClaonBack/post/repository/ClimbingHistoryRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java
  src/main/java/coLaon/ClaonBack/user/domain/Laon.java
  src/main/java/coLaon/ClaonBack/user/dto/LaonFindResponseDto.java
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepositorySupport.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/main/java/coLaon/ClaonBack/user/web/LaonController.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/repository/LaonRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/LaonServiceTest.java
Labels: refactor

#322 refac: add is owner to post detail dto
  src/main/java/coLaon/ClaonBack/post/dto/PostDetailResponseDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostReportRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: refactor

#321 refac: refactor dto of find all parent comment api
  src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/test/java/coLaon/ClaonBack/repository/PostCommentRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
Labels: refactor

#323 refac: add is owner in child comment response dto
  src/main/java/coLaon/ClaonBack/post/dto/ChildCommentResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepositorySupport.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
Labels: refactor
