Repository Co-Laon/claon-server, pull requests merged in 2022-07, with the labels that each got.

#64 feat: add oauth2 login with google and kakao
  .gitignore
  build.gradle
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java
  src/main/java/coLaon/ClaonBack/common/utils/JwtUtil.java
  src/main/java/coLaon/ClaonBack/config/CustomOAuth2UserService.java
  src/main/java/coLaon/ClaonBack/config/JwtAuthFilter.java
  src/main/java/coLaon/ClaonBack/config/JwtAuthenticationEntryPoint.java
  src/main/java/coLaon/ClaonBack/config/OAuth2FailureHandler.java
  src/main/java/coLaon/ClaonBack/config/OAuth2SuccessHandler.java
  src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/config/dto/JwtDto.java
  src/main/java/coLaon/ClaonBack/config/dto/OAuth2Dto.java
  src/main/java/coLaon/ClaonBack/post/Service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/Service/PostService.java
  src/main/java/coLaon/ClaonBack/post/domain/PostComment.java
  src/main/java/coLaon/ClaonBack/post/domain/PostLike.java
  src/main/java/coLaon/ClaonBack/post/dto/CommentResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/LikeRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/LikeResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepository.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/coLaon/ClaonBack/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
Labels: enhancement

#71 feat: add server start script
  .gitignore
Labels: chore

#77 docs: modify pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, refactor

#75 refac: refactor google and kakao sign in
  build.gradle
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java
  src/main/java/coLaon/ClaonBack/common/utils/JwtUtil.java
  src/main/java/coLaon/ClaonBack/config/CustomOAuth2UserService.java
  src/main/java/coLaon/ClaonBack/config/JwtAuthFilter.java
  src/main/java/coLaon/ClaonBack/config/OAuth2FailureHandler.java
  src/main/java/coLaon/ClaonBack/config/OAuth2SuccessHandler.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/config/dto/JwtDto.java
  src/main/java/coLaon/ClaonBack/config/dto/OAuth2Dto.java
  src/main/java/coLaon/ClaonBack/post/dto/ChildCommentResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java
  src/main/java/coLaon/ClaonBack/user/domain/OAuth2Provider.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/OAuth2UserInfoDto.java
  src/main/java/coLaon/ClaonBack/user/dto/SignInRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/infra/GoogleUserInfoProvider.java
  src/main/java/coLaon/ClaonBack/user/infra/KakaoUserInfoProvider.java
  src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java
  src/main/java/coLaon/ClaonBack/user/service/OAuth2UserInfoProvider.java
  src/main/java/coLaon/ClaonBack/user/service/OAuth2UserInfoProviderSupplier.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/test/java/coLaon/ClaonBack/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
Labels: refactor

#78 fix: fix bug in oauth login
  src/main/java/coLaon/ClaonBack/user/infra/GoogleUserInfoProvider.java
  src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java
Labels: fix

#79 fix: fix bug in sign-in
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
Labels: fix

#80 fix: fix bug in cookie util
  src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java
Labels: fix

#72 feat: implement find like
  src/main/java/coLaon/ClaonBack/post/dto/ChildCommentResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/LikeFindResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
Labels: enhancement

#68 feat: implement Create, Delete Laon
  src/main/java/coLaon/ClaonBack/user/domain/Laon.java
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/web/LaonController.java
  src/test/java/coLaon/ClaonBack/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
Labels: enhancement

#81 refac: refactor code style, endpoint, and error message
  src/main/java/coLaon/ClaonBack/common/domain/BaseEntity.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/BasicLocalArea.java
  src/main/java/coLaon/ClaonBack/common/domain/enums/MetropolitanArea.java
  src/main/java/coLaon/ClaonBack/common/exception/BadRequestException.java
  src/main/java/coLaon/ClaonBack/common/exception/BaseRuntimeException.java
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/common/exception/InternalServerErrorException.java
  src/main/java/coLaon/ClaonBack/common/exception/UnauthorizedException.java
  src/main/java/coLaon/ClaonBack/common/exception/UnavailableMailServerException.java
  src/main/java/coLaon/ClaonBack/common/infrastructure/EmailSender.java
  src/main/java/coLaon/ClaonBack/common/infrastructure/RelativeTimeString.java
  src/main/java/coLaon/ClaonBack/common/validator/IdEqualValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/IsDeletedValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/Validator.java
  src/main/java/coLaon/ClaonBack/config/EmailSenderConfig.java
  src/main/java/coLaon/ClaonBack/config/SwaggerConfig.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/config/dto/JwtDto.java
  src/main/java/coLaon/ClaonBack/post/domain/PostComment.java
  src/main/java/coLaon/ClaonBack/post/domain/PostLike.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/domain/Laon.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/infra/GoogleUserInfoProvider.java
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/web/LaonController.java
  src/test/java/coLaon/ClaonBack/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
Labels: refactor

#82 refactor: implement comment view more
  src/main/java/coLaon/ClaonBack/post/dto/CommentFindResponseDto.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
Labels: refactor

#93 feat: add centor entity
  build.gradle
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterImg.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterImgListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/Charge.java
  src/main/java/coLaon/ClaonBack/center/domain/ChargeListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java
  src/main/java/coLaon/ClaonBack/center/domain/ObjectListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/OperatingTime.java
  src/main/java/coLaon/ClaonBack/center/domain/OperatingTimeListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java
  src/main/java/coLaon/ClaonBack/center/domain/SectorInfoListConverter.java
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java
  src/main/java/coLaon/ClaonBack/center/repository/HoldInfoRepository.java
  src/main/java/coLaon/ClaonBack/common/utils/CookieUtil.java
  src/main/java/coLaon/ClaonBack/common/utils/JwtUtil.java
Labels: enhancement

#94 feat: implement set user private account
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/dto/PublicScopeResponseDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/UserServiceTest.java
Labels: enhancement

#96 feat: add create center
  src/main/java/coLaon/ClaonBack/center/domain/Center.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterImg.java
  src/main/java/coLaon/ClaonBack/center/domain/CenterImgListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/Charge.java
  src/main/java/coLaon/ClaonBack/center/domain/ChargeListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/HoldInfo.java
  src/main/java/coLaon/ClaonBack/center/domain/OperatingTime.java
  src/main/java/coLaon/ClaonBack/center/domain/OperatingTimeListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/SectorInfo.java
  src/main/java/coLaon/ClaonBack/center/domain/SectorInfoListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/converter/CenterImgListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/converter/ChargeListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/converter/ObjectListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/converter/OperatingTimeListConverter.java
  src/main/java/coLaon/ClaonBack/center/domain/converter/SectorInfoListConverter.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/CenterResponseDto.java
  src/main/java/coLaon/ClaonBack/center/dto/HoldInfoRequestDto.java
  src/main/java/coLaon/ClaonBack/center/dto/HoldInfoResponseDto.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/common/validator/IsAdminValidator.java
  src/test/java/coLaon/ClaonBack/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/LaonServiceTest.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
Labels: enhancement

#102 feat: implement create post and post validator (#42)
  src/main/java/coLaon/ClaonBack/common/validator/ContentsCountValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/ContentsImageFormatValidator.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/domain/PostContents.java
  src/main/java/coLaon/ClaonBack/post/dto/PostContentsDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
Labels: enhancement

#105 feat: add global exception handler
  src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/common/exception/ExceptionDto.java
  src/main/java/coLaon/ClaonBack/common/exception/ServiceUnavailableException.java
  src/main/java/coLaon/ClaonBack/common/exception/UnavailableMailServerException.java
  src/main/java/coLaon/ClaonBack/common/infrastructure/EmailSender.java
Labels: enhancement

#103 feat: add pagination
  src/main/java/coLaon/ClaonBack/common/domain/Pagination.java
  src/main/java/coLaon/ClaonBack/common/domain/PaginationFactory.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/UserServiceTest.java
Labels: enhancement

#99 feat: add get user info of instagram
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/user/dto/InstagramResponseDto.java
  src/main/java/coLaon/ClaonBack/user/infra/InstagramUserInfoProvider.java
  src/main/java/coLaon/ClaonBack/user/service/OAuth2UserInfoProviderSupplier.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/AuthController.java
  src/test/java/coLaon/ClaonBack/AuthServiceTest.java
Labels: enhancement

#97 feat: s3 setting
  build.gradle
  src/main/java/coLaon/ClaonBack/common/exception/ErrorCode.java
  src/main/java/coLaon/ClaonBack/common/infrastructure/S3Uploader.java
  src/main/java/coLaon/ClaonBack/common/validator/IsImageValidator.java
  src/main/java/coLaon/ClaonBack/config/AmazonS3Config.java
  src/main/java/coLaon/ClaonBack/storage/domain/enums/Purpose.java
  src/main/java/coLaon/ClaonBack/storage/service/StorageService.java
  src/main/java/coLaon/ClaonBack/storage/web/StorageController.java
  src/main/java/coLaon/ClaonBack/user/repository/UserRepository.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: enhancement

#106 refac: refactor code post create and test code
  src/main/java/coLaon/ClaonBack/common/validator/ContentsCountValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/ContentsImageFormatValidator.java
  src/main/java/coLaon/ClaonBack/common/validator/PostContentsSize.java
  src/main/java/coLaon/ClaonBack/common/validator/PostContentsSizeValidator.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/domain/PostContents.java
  src/main/java/coLaon/ClaonBack/post/dto/PostContentsDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/test/java/coLaon/ClaonBack/AuthServiceTest.java
  src/test/java/coLaon/ClaonBack/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/PostServiceTest.java
Labels: refactor

#122 fix: fix bug in global exception handler
  src/main/java/coLaon/ClaonBack/common/GlobalExceptionHandler.java
  src/main/java/coLaon/ClaonBack/common/exception/ConstraintExceptionDto.java
  src/main/java/coLaon/ClaonBack/common/exception/ExceptionDto.java
  src/main/java/coLaon/ClaonBack/common/exception/MethodArgumentNotValidExceptionDto.java
  src/main/java/coLaon/ClaonBack/common/validator/PostContentsSizeValidator.java
Labels: fix

#108 feat:implement block user
  src/main/java/coLaon/ClaonBack/user/domain/BlockUser.java
  src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: enhancement

#134 fix: init is deleted and is private of user when create user
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: fix

#135 fix: fix count comment which is not deleted
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
Labels: fix

#139 fix: fix delete method and variable input
  src/main/java/coLaon/ClaonBack/post/dto/LikeFindResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/LikeRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: refactor

#136 refac: refactor remove laon when block user
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: refactor

#140 feat: implement find block user list (#101)
  src/main/java/coLaon/ClaonBack/user/dto/BlockUserFindResponseDto.java
  src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: enhancement

#150 feat: implement search center name by keyword
  src/main/java/coLaon/ClaonBack/center/repository/CenterRepository.java
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
Labels: enhancement

#152 refac: implement additional validator (constraints) for user nickname…
  src/main/java/coLaon/ClaonBack/common/validator/UserNickname.java
  src/main/java/coLaon/ClaonBack/common/validator/UserNicknameValidator.java
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/dto/UserModifyRequestDto.java
Labels: refactor

#159 refac: delete guest mode
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/center/web/CenterController.java
  src/main/java/coLaon/ClaonBack/config/WebSecurityConfig.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: refactor

#160 refac: refactor for soft delete
  src/main/java/coLaon/ClaonBack/center/service/CenterService.java
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/ReviewRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/user/domain/User.java
  src/main/java/coLaon/ClaonBack/user/service/LaonService.java
  src/test/java/coLaon/ClaonBack/service/CenterServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: refactor

#162 fix: fix bug of all repository
  src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java
Labels: fix

#142 feat: public user api
  build.gradle
  src/main/java/coLaon/ClaonBack/center/dto/HoldInfoKey.java
  src/main/java/coLaon/ClaonBack/post/domain/ClimbingHistory.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/dto/CenterClimbingHistoryResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/ClimbingHistoryRequestDto.java
  src/main/java/coLaon/ClaonBack/post/dto/ClimbingHistoryResponseDto.java
  src/main/java/coLaon/ClaonBack/post/dto/PostCreateRequestDto.java
  src/main/java/coLaon/ClaonBack/post/repository/ClimbingHistoryRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostLikeRepository.java
  src/main/java/coLaon/ClaonBack/post/repository/PostRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/user/dto/IndividualUserResponseDto.java
  src/main/java/coLaon/ClaonBack/user/repository/LaonRepository.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
  src/test/java/coLaon/ClaonBack/repository/ClimbingHistoryRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostLikeRepositoryTest.java
  src/test/java/coLaon/ClaonBack/repository/PostRepositoryTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
  src/test/java/coLaon/ClaonBack/service/UserServiceTest.java
Labels: enhancement

#156 feat: find post
  src/main/java/coLaon/ClaonBack/common/validator/IsPrivateValidator.java
  src/main/java/coLaon/ClaonBack/post/domain/Post.java
  src/main/java/coLaon/ClaonBack/post/dto/PostResponseDto.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
  src/main/java/coLaon/ClaonBack/user/repository/BlockUserRepository.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: enhancement
