Repository Co-Laon/claon-server, pull requests merged in 2023-11, with the labels that each got.

#400 refac: add status code config for circuit of gateway
  gateway/src/main/resources/application.yml
Labels: refactor

#401 feat: add docker-compose and build task for each module
  README.md
  auth/Dockerfile
  build.gradle
  center/Dockerfile
  discovery/Dockerfile
  docker-compose.yml
  gateway/Dockerfile
  monitor/Dockerfile
  post/Dockerfile
  user/Dockerfile
Labels: enhancement

#402 refac: refactor docker-compose and resource
  auth/src/main/resources/application.yml
  center/src/main/resources/application.yml
  docker-compose.yml
  gateway/src/main/resources/application.yml
  post/src/main/resources/application.yml
  user/src/main/resources/application.yml
Labels: refactor

#394 docs: add spring cloud eureka and open feign and monitoring docs
  docs/Monitoring.md
  docs/SpringCloudEureka.md
  docs/SpringCloudOpenFeign.md
Labels: documentation

#393 docs: add docs for springboot admin (#4)
  docs/SpringBootAdmin.md
  docs/images/SpringBootAdmin/dashboard.png
  docs/images/SpringBootAdmin/instance.png
  docs/images/SpringBootAdmin/log-in.png
  docs/images/SpringBootAdmin/log.png
  docs/images/SpringBootAdmin/non-security.png
  docs/images/SpringBootAdmin/web-access.png
Labels: documentation

#397 docs: add docs for spring cloud gateway (#4)
  docs/SpringCloudGateway.md
  docs/images/spring-cloud-gateway-architecture.png
Labels: documentation

#404 docs: refactor docs
  README.md
  build.gradle
  docs/Monitoring.md
  docs/ResiliencyPattern.md
  docs/SpringBootAdmin.md
  docs/SpringCloudEureka.md
  docs/SpringCloudGateway.md
  docs/SpringCloudOpenFeign.md
  docs/actuator.md
  docs/discovery.md
  docs/eureka.md
  docs/gateway.md
  docs/images/SpringBootAdmin/dashboard.png
  docs/images/SpringBootAdmin/instance.png
  docs/images/SpringBootAdmin/log-in.png
  docs/images/SpringBootAdmin/log.png
  docs/images/SpringBootAdmin/non-security.png
  docs/images/SpringBootAdmin/web-access.png
  docs/images/eureka.png
  docs/images/resiliency-pattern-circuit-bulkhead.png
  docs/images/resiliency-pattern-circuit-picture.png
  docs/images/resiliency-pattern-rate-limiter.png
  docs/images/spring-cloud-gateway-architecture.png
  docs/micrometer_zipkin.md
  docs/monitor.md
  docs/openfeign.md
  docs/resilience4j.md
  docs/service.md
  docs/spring_boot_admin.md
  docs/spring_cloud_gateway.md
  gateway/src/main/resources/application.yml
Labels: documentation

#406 chore: refactor ci and cd
  .github/workflows/cd.yml
  .github/workflows/ci-cloud.yml
  .github/workflows/ci.yml
Labels: chore
