Repository Co-Laon/claon-server, pull requests merged in 2023-02, with the labels that each got.

#338 fix: add private and block check of post, post like, and post comment
  src/main/java/coLaon/ClaonBack/post/repository/PostCommentRepository.java
  src/main/java/coLaon/ClaonBack/post/service/PostCommentService.java
  src/main/java/coLaon/ClaonBack/post/service/PostLikeService.java
  src/main/java/coLaon/ClaonBack/post/service/PostService.java
  src/test/java/coLaon/ClaonBack/service/PostCommentServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostLikeServiceTest.java
  src/test/java/coLaon/ClaonBack/service/PostServiceTest.java
Labels: fix

#341 fix: fix bug about redis template delete key
  src/main/java/coLaon/ClaonBack/common/utils/RefreshTokenUtil.java
  src/main/java/coLaon/ClaonBack/user/web/UserController.java
Labels: fix

#342 refac: refactor search user to exclude not sign up user
  src/main/java/coLaon/ClaonBack/user/repository/UserRepositorySupport.java
Labels: refactor

#340 add duplicated name check and sign up controller test and spring restdocs
  build.gradle
  src/main/java/coLaon/ClaonBack/user/dto/SignUpRequestDto.java
  src/main/java/coLaon/ClaonBack/user/service/UserService.java
  src/main/resources/static/docs/index.adoc
  src/test/java/coLaon/ClaonBack/controller/AuthControllerTest.java
  src/test/java/coLaon/ClaonBack/controller/utils/SpringRestDocsUtils.java
  src/test/java/coLaon/ClaonBack/controller/utils/UserDetailsArgumentResolver.java
  src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: enhancement

#339 feat: construct codecov (#333)
  .github/workflows/ci.yml
  README.md
  build.gradle
  codecov.yml
Labels: enhancement

#335 feat: 로거 도입
  .gitignore
  src/main/java/coLaon/ClaonBack/config/InterceptorConfig.java
  src/main/java/coLaon/ClaonBack/config/TraceIdInterceptor.java
  src/main/resources/logback-spring.xml
Labels: enhancement

#343 feat: add info log in interceptor
  src/main/java/coLaon/ClaonBack/config/RequestLoggingFilterConfig.java
  src/main/java/coLaon/ClaonBack/config/TraceIdInterceptor.java
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
Labels: enhancement

#344 refac: refactor delete post contents from body to header
  src/main/java/coLaon/ClaonBack/post/web/PostController.java
Labels: refactor

#345 refac: refactor request log to except image
  .gitignore
  src/main/java/coLaon/ClaonBack/config/RequestLoggingFilterConfig.java
  src/main/java/coLaon/ClaonBack/config/TraceIdInterceptor.java
Labels: refactor

#346 refac: move logging interceptor to filter
  src/main/java/coLaon/ClaonBack/config/CustomServletWrappingFilter.java
  src/main/java/coLaon/ClaonBack/config/TraceIdInterceptor.java
Labels: refactor
